### ISSUE TITLE
email not valid in contrib?

### ISSUE THREAD

**Issue by axfelix** [substance/dar#1]
Hi folks,

![image](https://user-images.githubusercontent.com/252047/36232663-8b8a2f78-1197-11e8-93b8-72f0eab52c9d.png)

did we somehow leave this one out of the spec?

**Comment by michael** [comment]
True, I will add that. 

Please keep the issues in the Texture repo, just so we have the communication in one place.

**Comment by axfelix** [comment]
OK, will do, thanks!
