### ISSUE TITLE
"name not valid in contrib" error

### ISSUE THREAD

**Issue by axfelix** [substance/dar#2]
![image](https://user-images.githubusercontent.com/252047/36232731-c43e1f00-1197-11e8-88e3-24f57772e771.png)

source data looks like this:

        <contrib contrib-type="author">
          <name><given-names>M. Teplan</given-names></name>
          <xref ref-type="aff" rid="aff0">0</xref>
        </contrib>

Can't quite tell what's wrong here.

**Comment by michael** [comment]
We need to fail earlier here. The reason is that contrib-group must be tagged with content-type="author". See this issue: https://github.com/substance/texture/issues/385
